name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./front-end-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Manage NPM Dependencies
        # Utiliza la acción que hemos creado. Importante que no vaya con ""
        uses: ./.github/actions/cache-node-dependencies
        with:
          # Pasamos los valores para los parámetros de la action
          app-name: "react-app"
          working-directory: "./front-end-app"

      - name: Build
        run: npm run build
