name: Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./front-end-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para que se descargue todo el historial de git y enviarlo a SonarCloud. Por defecto es 1, que sólo descarga el último commit.
      - name: Manage NPM Dependencies
        uses: ./.github/actions/cache-node-dependencies
        with:
          app-name: "react-app"
          working-directory: "./front-end-app"

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run ci:lint # Ejecuta el comando npm run ci:lint de nuestro repositorio. Asegurarnos que tengamos un script en el package.json que ejecute el linter que estemos usando, en este caso ESlint

      - name: Test
        run: npm run ci:test # Ejecuta el comando npm run ci:test de nuestro repositorio. Asegurarnos que tengamos un script en el package.json que ejecute el runner de testing que estemos usando

      - name: SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with: # Muy importante esta parte, ya que le dice a SonarCloud que sólo analice el proyecto de front
          projectBaseDir: front-end-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
